routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Routes de l'Authentification
Auth::routes();

//Les routes pour les Utilisateurs du site -> FRONT
Route::group(['middleware'=>'auth'],function () {
  //La route qui redirige sur mon front
  Route::get('/', 'FrontController@index')->name('front');
  //La route qui redirige vers le panel user
  Route::resource('config', 'ConfigUserController');
  //La route qui redirife vers l'offre selected
  Route::get('offre/{id}', 'FrontController@show')->name('frontoffre');

  Route::post('look','FrontController@filter')->name('frontoffrefilter');
  // La route qui permet de realiser des filtres
  Route::post('filter','FrontController@filters')->name('frontoffrefilters');
  });
  //La route qui redirife vers l'offre selected
  Route::get('pdf', 'FrontController@pdf')->name('frontoffrepdf');

//Les routes pour les Admins du site -> BACK
Route::group(['middleware'=>'auth','middleware'=>'admin'],function () {

  //Route Affichage DASHBOARD
  Route::resource('back/dashboard', 'DashboardController');

  //Route gestion OFFRE
  Route::resource('back/offre', 'OffreController');

  //Route gestion ENTREPRISE
  Route::resource('back/entreprise', 'EntrepriseController');

  //Route gestion UTILISATEUR
  Route::resource('back/utilisateur', 'UtilisateurController');

});

//Les routes pour les Entreprises du site -> BACK
Route::group(['middleware'=>'auth','middleware'=>'entreprise'],function () {

  //Route gestion OFFRE
  Route::resource('back/offres_entreprise', 'EntrepriseOffreController');
});

app/Entreprise.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entreprise extends Model
{
    //
    public function offres()
    {
        return $this->hasMany('App\Offre');
    }
}

app/Http/Controllers/BackController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackController extends Controller
{
    //
    public function index(){
      return view ('layouts.templateBack');
    }
}

app/Http/Controllers/EntrepriseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Entreprise;
use Validator;

class EntrepriseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lesEntreprises = Entreprise::All();
        return view("back.entreprise.index")->with("lesEntreprises", $lesEntreprises);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("back.entreprise.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nom' => 'required',
            'ville' => 'required',
            'codePostal' => 'required',
            'adresse' => 'required',
            'contact' => 'required',
            'telephone' => 'required',
            'mail' => 'required',
          ]);
        if ($validator->fails()){
           return redirect()->route("entreprise.create")->withErrors($validator)->withInput();
        }

        //les inputs font référence à tes name de ton formulaire, GL pour la suite Arthur :)
        $entreprise = new Entreprise;
        $entreprise->nom = $request->input('nom');
        $entreprise->ville = $request->input('ville');
        $entreprise->codePostal = $request->input('codePostal');
        $entreprise->adresse = $request->input('adresse');
        $entreprise->contact = $request->input('contact');
        $entreprise->telephone = $request->input('telephone');
        $entreprise->mail = $request->input('mail');
        $entreprise->map = $request->input('map');
        $entreprise->save();

        return redirect()->route("entreprise.index")->with('success','Création réussite !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entreprise = Entreprise::find($id);
        return view('back.entreprise.edit')->with('entreprise', $entreprise);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'nom' => 'required',
            'ville' => 'required',
            'codePostal' => 'required',
            'adresse' => 'required',
            'contact' => 'required',
            'telephone' => 'required',
            'mail' => 'required',
          ]);
        if ($validator->fails()){
           return redirect()->route("entreprise.edit",$id)->withErrors($validator)->withInput();
        }

        $entreprise = Entreprise::find($id);
        $entreprise->nom = $request->input('nom');
        $entreprise->ville = $request->input('ville');
        $entreprise->codePostal = $request->input('codePostal');
        $entreprise->adresse = $request->input('adresse');
        $entreprise->contact = $request->input('contact');
        $entreprise->telephone = $request->input('telephone');
        $entreprise->mail = $request->input('mail');
        $entreprise->map = $request->input('map');
        $entreprise->save();

        return redirect()->route("entreprise.index")->with('success','Modification réussite !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Entreprise::find($id)->delete();

        return redirect()->route("entreprise.index")->with('warning','Suppression réussite !');
    }
}

resources/views/back/entreprise/create.blade.php
@extends('layouts.templateBack')
@section('titre')
   Ajouter une entreprise
@stop

@section('contenu')

<text style='margin-left:10px;color:red;'>* Champs obligatoires</text>
<br> </br>

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

<form style='margin-left:10px;' method="POST" action="{{route('entreprise.store')}}">
@csrf
  <div class="form-group">
    <label for="Nom">Nom *</label>
    <input type="text" class="form-control" id="nom" name="nom" placeholder="Entrer le nom">
  </div>
  <div class="form-group">
    <label for="ville">Ville *</label>
    <input type="text" class="form-control" id="ville" name="ville" placeholder="Entrer la ville">
  </div>
  <div class="form-group">
    <label for="codePostal">Code Postal *</label>
    <input type="text" class="form-control" id="codePostal" name="codePostal" placeholder="Entrer le code postal">
  </div>
  <div class="form-group">
    <label for="adresse">Adresse *</label>
    <input type="text" class="form-control" id="adresse" name="adresse" placeholder="Entrer l'adresse">
  </div>
  <div class="form-group">
    <label for="contact">Contact *</label>
    <input type="text" class="form-control" id="contact" name="contact" placeholder="Entrer le nom du contact">
  </div>
  <div class="form-group">
    <label for="telephone">Téléphone *</label>
    <input type="text" class="form-control" id="telephone" name="telephone" placeholder="Entrer le numéro de téléphone">
  </div>
  <div class="form-group">
    <label for="mail">Mail *</label>
    <input type="text" class="form-control" id="mail" name="mail" placeholder="Entrer l'adresse mail">
  </div>
  <div class="form-group">
    <label for="adresse">Carte google MAP</label>
    <input type="text" class="form-control" id="map" name="map" placeholder=" exemple : https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2714.020020207576!2d5.44144331581544!3d47.13787382823184!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f2b2ee6179ebd7%3A0xdad657b1d7ce569a!2s18%20Rue%20de%20la%20Chapelle%2C%2039290%20Biarne!5e0!3m2!1sfr!2sfr!4v1588507517102!5m2!1sfr!2sfr-hidden= ">
  </div>
    <button style='margin-bottom:10px;' type="submit" class="btn btn-primary">
        Créer
    </button>
  </form>

@endsection

resources/views/back/entreprise/edit.blade.php
@extends('layouts.templateBack')
@section('titre')
   Modifier l'entreprise '{{$entreprise->nom}}'
@stop

@section('contenu')

<text style='margin-left:10px;color:red;'>* Champs obligatoires</text>
<br> </br>

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

<form style='margin-left:10px;' method="POST" action="{{route('entreprise.update', $entreprise->id)}}">
@csrf
@method('PUT')
  <div class="form-group">
    <label for="Nom">Nom *</label>
    <input type="text" class="form-control" id="nom" name="nom" value="{{$entreprise->nom}}">
  </div>
  <div class="form-group">
    <label for="ville">Ville *</label>
    <input type="text" class="form-control" id="ville" name="ville" value="{{$entreprise->ville}}">
  </div>
  <div class="form-group">
    <label for="codePostal">Code Postal *</label>
    <input type="text" class="form-control" id="codePostal" name="codePostal" value="{{$entreprise->codePostal}}">
  </div>
  <div class="form-group">
    <label for="adresse">Adresse *</label>
    <input type="text" class="form-control" id="adresse" name="adresse" value="{{$entreprise->adresse}}">
  </div>
  <div class="form-group">
    <label for="contact">Contact *</label>
    <input type="text" class="form-control" id="contact" name="contact" value="{{$entreprise->contact}}">
  </div>
  <div class="form-group">
    <label for="telephone">Téléphone *</label>
    <input type="text" class="form-control" id="telephone" name="telephone" value="{{$entreprise->telephone}}">
  </div>
  <div class="form-group">
    <label for="mail">Mail *</label>
    <input type="text" class="form-control" id="mail" name="mail" value="{{$entreprise->mail}}">
  </div>
  <div class="form-group">
    <label for="adresse">Carte google MAP</label>
    <input type="text" class="form-control" id="map" name="map" value="{{$entreprise->map}}">
  </div>

    <button style='margin-bottom:10px;' type="submit" class="btn btn-primary">
        Modifier
    </button>
  </form>

@endsection

resources/views/back/entreprise/index.blade.php
@extends('layouts.templateBack')
@section('titre')
   Liste des Entreprises
@stop

@section('contenu')
<table class="table table-sm" id="table_id">

    <a href="{{route('entreprise.create')}}">
        <button style='margin-left:10px;' type="submit" class="btn btn-primary">
        Ajouter une entreprise
        </button>
    </a>
    <br> </br>

    @include('back.alert-message')

    <thead>
      <tr>
          <th scope="col">ID</th>
          <th scope="col">Nom</th>
          <th scope="col">Ville</th>
          <th scope="col">Code Postal</th>
          <th scope="col">Adresse</th>
          <th scope="col">Contact</th>
          <th scope="col">Téléphone</th>
          <th scope="col">Mail</th>
          <th scope="col" class="text-right">Action</th>
      </tr>
    </thead>
    <tbody>

    @foreach($lesEntreprises as $entreprise)
      <tr>

        <td> {{$entreprise->id}} </td>
        <td> {{$entreprise->nom}} </td>
        <td> {{$entreprise->ville}} </td>
        <td> {{$entreprise->codePostal}} </td>
        <td> {{$entreprise->adresse}} </td>
        <td> {{$entreprise->contact}} </td>
        <td> {{$entreprise->telephone}} </td>
        <td> {{$entreprise->mail}} </td>

        <td class="td-actions text-right">
            <div style="display: inline-flex;">
        <form action="{{route('entreprise.edit', $entreprise->id)}}" method="POST">
            @csrf
            @method('GET')
          <button type="submit" rel="tooltip" class="btn btn-success btn-round">
              <i class="material-icons">Modifier</i>
          </button>
        </form>
            <form action="{{route('entreprise.destroy', $entreprise->id)}}" method="POST">
            @csrf
            @method('DELETE')
          <button type="submit" rel="tooltip" class="btn btn-danger btn-round" onclick="return confirm('Est tu sur de vouloir supprimer cette entreprise ?')">
              <i class="material-icons">Supprimer</i>
          </button>
            </form>
          </div>
        </td>
      </tr>
    @endforeach

    </tbody>
  </table>  
@stop

@section('script')
  <script>
  $(document).ready(function() {
          $('#table_id').DataTable({

              "language": {
                  "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
              }
          });
      });
  </script>
@stop