routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Routes de l'Authentification
Auth::routes();

//Les routes pour les Utilisateurs du site -> FRONT
Route::group(['middleware'=>'auth'],function () {
  //La route qui redirige sur mon front
  Route::get('/', 'FrontController@index')->name('front');
  //La route qui redirige vers le panel user
  Route::resource('config', 'ConfigUserController');
  //La route qui redirife vers l'offre selected
  Route::get('offre/{id}', 'FrontController@show')->name('frontoffre');

  Route::post('look','FrontController@filter')->name('frontoffrefilter');
  // La route qui permet de realiser des filtres
  Route::post('filter','FrontController@filters')->name('frontoffrefilters');
  });
  //La route qui redirife vers l'offre selected
  Route::get('pdf', 'FrontController@pdf')->name('frontoffrepdf');

//Les routes pour les Admins du site -> BACK
Route::group(['middleware'=>'auth','middleware'=>'admin'],function () {

  //Route Affichage DASHBOARD
  Route::resource('back/dashboard', 'DashboardController');

  //Route gestion OFFRE
  Route::resource('back/offre', 'OffreController');

  //Route gestion ENTREPRISE
  Route::resource('back/entreprise', 'EntrepriseController');

  //Route gestion UTILISATEUR
  Route::resource('back/utilisateur', 'UtilisateurController');

});

//Les routes pour les Entreprises du site -> BACK
Route::group(['middleware'=>'auth','middleware'=>'entreprise'],function () {

  //Route gestion OFFRE
  Route::resource('back/offres_entreprise', 'EntrepriseOffreController');
});

resources/views/layouts/templateAut.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
	<title>HDA</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{url('images/favicon.ico')}}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/bootstrap.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/font-awesome.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/animate.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/hamburgers.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/select2.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/util.css')}}">
	<link rel="stylesheet" type="text/css" href="{{url('css/main.css')}}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
        <!-- Main content -->
        @section("contenu")

        @show
        <!-- /.content -->
			</div>
		</div>
	</div>




<!--===============================================================================================-->
	<script src="{{url('js/jquery-3.2.1.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url('js/popper.js')}}"></script>
	<script src="{{url('js/bootstrap.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url('js/select2.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url('js/tilt.jquery.min.js')}}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{{url('js/main.js')}}"></script>

</body>
</html>

resources/views/layouts/templateBack.blade.php
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Back-Office</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{url('plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{url('css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- DATATABLE -->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css"/>

</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->

    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{route('front')}}" class="nav-link">Accueil</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
          <i class="fas fa-sign-out-alt"></i> Se déconnecter</a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
      </li>
    </ul>
  </nav>
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <?php
      $statut = auth()->user();
      $statut = $statut->statut;
      ?>
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          @if ($statut == "Administrateur")
            <li class="nav-item">
              <a href="{{ route('dashboard.index')}}" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                  Dashboard
                </p>
              </a>
            </li>
          <li class="nav-item">
            <a href="{{ route('offre.index')}}" class="nav-link">
              <i class="nav-icon fas fa-archive"></i>
              <p>
                Gestion Offres
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{{ route('entreprise.index')}}" class="nav-link">
              <i class="nav-icon fas fa-building"></i>
              <p>
                Gestion Entreprises
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('utilisateur.index')}}" class="nav-link">
              <i class="nav-icon fas fa-user"></i>
              <p>
                Gestion Utilisateurs
              </p>
            </a>
          </li>
        @endif
        @if ($statut == "Entreprise")
        <li class="nav-item">
          <a href="{{ route('offres_entreprise.index')}}" class="nav-link">
            <i class="nav-icon fas fa-archive"></i>
            <p>
              Gestion Offres
            </p>
          </a>
        </li>
      @endif
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
            <p style='margin: auto; font-size:40px;'><b>
@section("titre")
@show

            </b></p>
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>


    <!-- Main content -->
    @section("contenu")

    @show
    <!-- /.content -->
  </div>

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{url('plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{url('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{url('js/adminlte.min.js')}}"></script>
<!-- DATATABLE -->
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>

@yield("script")

</body>
</html>

resources/views/layouts/templateFront.blade.php
</html>
<!DOCTYPE html>
<html lang="fr">
<head>
	<title>HDA</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{url('images/favicon.ico')}}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/bootstrap.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/font-awesome.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url('css/animate.css')}}">
<!--===============================================================================================-->
<link rel="stylesheet" href="{{url('css/all.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{{url('css/adminlte.min.css')}}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{{url('css/select2.min.css')}}">
<!--===============================================================================================-->

	<link rel="stylesheet" type="text/css" href="{{url('css/main.css')}}">
  <!-- Bootstrap CSS -->
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{url('plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{{url('css/card.css')}}">

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-163820930-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-163820930-1');
</script>

</head>
<body>
  <!-- Navbar -->
<nav style="margin-left: 0px;" class="main-header navbar navbar-expand navbar-white navbar-light">
<!-- SEARCH FORM -->
<li class="nav-item">
	<a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{{route('front')}}" role="button">
<i class="fas fa-home"></i>
	</a>
</li>
<form class="form-inline ml-3" method="post" action="{{route('frontoffrefilter')}}">
	@csrf
<div class="input-group input-group-sm">
  <input class="form-control form-control-navbar" name="search" id="search" type="search" placeholder="Search" aria-label="Search">
  <div class="input-group-append">
    <button class="btn btn-navbar" type="submit">
      <i class="fas fa-search"></i>
    </button>
  </div>
</div>
</form>
<?php $user = auth()->user();?>
<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">

@if ($user->statut == 'Administrateur')
	<!-- Btn back office ADMIN -->
	<li class="nav-item">
	  <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{{ route('dashboard.index') }}" role="button">
	<i class="fas fa-tools"></i>
	  </a>
	</li>
@endif

@if ($user->statut == 'Entreprise')
	<!-- Btn back office ENTREPRISE -->
	<li class="nav-item">
	  <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{{ route('offres_entreprise.index') }}" role="button">
			<i class="fas fa-plus-square"></i>
	  </a>
	</li>
@endif

<!-- Btn param user-->
<li class="nav-item">
  <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{{ route('config.index') }}" role="button">
      <i class="fas fa-cog"></i>
  </a>
</li>
<!-- Btn log out -->
<li class="nav-item">
  <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
    <i class="fas fa-sign-out-alt"></i> Se déconnecter</a>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
      @csrf
  </form>
</li>
</nav>


	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
        <div class="content_card">
          @section('contenu')
          @show
        </div>

			</div>
		</div>
	</div>




<!--===============================================================================================-->
	<script src="{{url('js/jquery-3.2.1.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url('js/popper.js')}}"></script>
	<script src="{{url('js/bootstrap.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url('js/select2.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url('js/tilt.jquery.min.js')}}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{{url('js/main.js')}}"></script>

</body>
</html>