routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Routes de l'Authentification
Auth::routes();

//Les routes pour les Utilisateurs du site -> FRONT
Route::group(['middleware'=>'auth'],function () {
  //La route qui redirige sur mon front
  Route::get('/', 'FrontController@index')->name('front');
  //La route qui redirige vers le panel user
  Route::resource('config', 'ConfigUserController');
  //La route qui redirife vers l'offre selected
  Route::get('offre/{id}', 'FrontController@show')->name('frontoffre');

  Route::post('look','FrontController@filter')->name('frontoffrefilter');
  // La route qui permet de realiser des filtres
  Route::post('filter','FrontController@filters')->name('frontoffrefilters');
  });
  //La route qui redirife vers l'offre selected
  Route::get('pdf', 'FrontController@pdf')->name('frontoffrepdf');

//Les routes pour les Admins du site -> BACK
Route::group(['middleware'=>'auth','middleware'=>'admin'],function () {

  //Route Affichage DASHBOARD
  Route::resource('back/dashboard', 'DashboardController');

  //Route gestion OFFRE
  Route::resource('back/offre', 'OffreController');

  //Route gestion ENTREPRISE
  Route::resource('back/entreprise', 'EntrepriseController');

  //Route gestion UTILISATEUR
  Route::resource('back/utilisateur', 'UtilisateurController');

});

//Les routes pour les Entreprises du site -> BACK
Route::group(['middleware'=>'auth','middleware'=>'entreprise'],function () {

  //Route gestion OFFRE
  Route::resource('back/offres_entreprise', 'EntrepriseOffreController');
});

app/Offre.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offre extends Model
{
    //
    public function entreprise()
    {
        return $this->belongsTo('App\Entreprise');
    }
}

app/Http/Controllers/BackController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackController extends Controller
{
    //
    public function index(){
      return view ('layouts.templateBack');
    }
}

app/Http/Controllers/OffreController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

use App\Notifications\OffreNotification;
use Illuminate\Support\Facades\Auth;
use App\Offre;
use App\Entreprise;
use App\User;
use Validator;


class OffreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lesOffres = Offre::all();
        return view("back.offre.index")->with("lesOffres",$lesOffres);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lesentreprises = Entreprise::all();
        $user = auth::user(); 
        return view("back.offre.create", compact('user', 'lesentreprises'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validator = Validator::make($request->all(), [
        'titre' => 'required',
        'intitule' => 'required',
        'description' => 'required',
        'secteur' => 'required',
        'niveau' => 'required',
        'contrat' => 'required',
        'entreprise' => 'required',
      ]);
      if ($validator->fails()){
        return redirect()->route("offre.create")->withErrors($validator)->withInput();
      }

        $offre = new Offre;
        $offre->titre =$request->input('titre');
        $offre->description =$request->input('description');
        $offre->intitule_poste =$request->input('intitule');
        $offre->niveau =$request->input('niveau');

        //Pour le PDF
        $rand = str_random(15);
        $pdf_upload = $request->file('file');
        if($pdf_upload != NULL){
          // Définition du chemin de stockage
          // Nommage du fichier
          $pdf_nommage = date('Y-m-d') . ' - ' . $rand .' - '. $pdf_upload->getClientOriginalName();
          // On indique le chemin du fichier pour la base de donnée
          $pdf_get = 'pdf\\' . $pdf_nommage;
          // Si il y a bien un fichier, on le déplace dans le répertoire et on stock le chemin dans la base de donnée
          if ($pdf_upload) {
              if ($pdf_upload->move('pdf', $pdf_nommage)) {
                $offre->pdf = $pdf_get;
              }
          } else {
              return redirect()->route('offres.index')->withStatus(__('Problème lors de l\'upload du PDF, veuillez essayer à nouveau.'));
          }
        }

        $offre->salaire =$request->input('salaire');
        $offre->secteur =$request->input('secteur');
        $offre->type_contrat =$request->input('contrat');
        $offre->entreprise_id =$request->input('entreprise');
        $offre->save();

        /**Envoie d'un mail à tout les utilisateurs lors de la création*/
        $lesUsers = User::all()->where('statut', 'Utilisateur');

        foreach ($lesUsers as $user) {
          $user->notify(new OffreNotification($offre->id));
        }

        return redirect()->route("offre.index")->with('success','Création réussite !');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $offre = Offre::find($id);
      $lesentreprises = Entreprise::all();

      return view('back.offre.edit')->with('offre', $offre)
                                    ->with("lesentreprises",$lesentreprises);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $validator = Validator::make($request->all(), [
        'titre' => 'required',
        'intitule' => 'required',
        'description' => 'required',
        'secteur' => 'required',
        'niveau' => 'required',
        'contrat' => 'required',
        'entreprise' => 'required',
      ]);
      if ($validator->fails()){
        return redirect()->route("offre.edit",$id)->withErrors($validator)->withInput();
      }
      $offre = Offre::find($id);
      $offre->titre = $request->input('titre');
      $offre->intitule_poste =$request->input('intitule');
      $offre->description =$request->input('description');
      $offre->niveau =$request->input('niveau');

      //Pour le PDF
      if ($request->file('file')!= NULL){
        unlink(public_path($offre->pdf));
        $rand = str_random(1500);
        $pdf_upload = $request->file('file');
        // Définition du chemin de stockage
        // Nommage du fichier
        $pdf_nommage = date('Y-m-d') . ' - '. $rand .' - '. $pdf_upload->getClientOriginalName();
        // On indique le chemin du fichier pour la base de donnée
        $pdf_get = 'pdf\\' . $pdf_nommage;
        // Si il y a bien un fichier, on le déplace dans le répertoire et on stock le chemin dans la base de donnée
        if ($pdf_upload) {
            if ($pdf_upload->move('pdf', $pdf_nommage)) {
              $offre->pdf =$pdf_get;
            }
        } else {
            return redirect()->route('offres.index')->withStatus(__('Problème lors de l\'upload du PDF, veuillez essayer à nouveau.'));
        }
      }

      $offre->salaire =$request->input('salaire');
      $offre->secteur =$request->input('secteur');
      $offre->type_contrat =$request->input('contrat');
      $offre->entreprise_id =$request->input('entreprise');
      $offre->save();

      return redirect()->route("offre.index")->with('success','Modification réussite !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $offre = Offre::find($id);
      if ($offre->pdf) {
        unlink(public_path($offre->pdf));
      }

      Offre::find($id)->delete();

      return redirect()->route("offre.index")->with('warning','Suppression réussite !');
    }
}

resources/views/back/offre/create.blade.php
@extends('layouts.templateBack')
@section('titre')
   Ajouter une offre
@stop

@section('contenu')

<text style='margin-left:10px;color:red;'>* Champs obligatoires</text>
<br> </br>

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

<form style='margin-left:10px;' method="POST" action="{{route('offre.store')}}" enctype="multipart/form-data">
@csrf
  <div class="form-group">
    <label for="Titre">Titre *</label>
    <input type="text" class="form-control" id="titre" name="titre" placeholder="Titre de l'offre">
  </div>

  <div class="form-group">
    <label for="Intitule_poste">Intitulé du poste *</label>
    <input type="text" class="form-control" id="intitule" name="intitule"  placeholder="Intitulé du poste"></textarea>
  </div>

  <div class="form-group">
    <label for="Secteur">Secteur *</label>
    <input type="text" class="form-control" id="secteur" name="secteur" placeholder="Secteur"></textarea>
  </div>

  <div class="form-group">
    <label for="Desciption">Description *</label>
    <textarea class="form-control" id="description" name="description" rows="5" placeholder="Description de l'offre"></textarea>
  </div>

  <div class="form-group">
     <label for="Niveau">Niveau *</label>
     <select class="form-control" id="niveau" name="niveau">
       <option>BAC</option>
       <option>BTS</option>
       <option>Licence</option>
       <option>Autre</option>
     </select>
  </div>

  <div class="form-group">
    <label for="Upload">Ajouter un PDF (file)</label>
     <div class="input-group mb-3">
       <div class="custom-file">
         <input type="file" id="file" name="file">
       </div>
     </div>
  </div>

  <div class="form-group">
    <label for="Contrat">Contrat *</label>
    <select class="form-control" id="contrat" name="contrat">
       <option>CDD</option>
       <option>CDI</option>
       <option>Contrat de professionnalisation</option>
       <option>Contrat d apprentissage</option>
     </select>
  </div>

  <div class="form-group">
    <label for="Salaire">Salaire</label>
    <input type="text" class="form-control" id="salaire" name="salaire"  placeholder="Salaire"></textarea>
  </div>


 <div class="form-group">
    <label for="ENTREPRISE">Entreprise *</label>
    <select class="form-control" id="entreprise" name="entreprise">
      <!--@if($user->statut != 'entreprise')-->
        @foreach ($lesentreprises as $entreprise)
        <option value="{{ $entreprise->id }}">{{ $entreprise->nom }}</option>
        @endforeach
      <!--@else
        <option value="{{   }}"></option>
      @endif-->
    </select>
  </div>

    <button style='margin-bottom:10px;' type="submit" class="btn btn-primary center-block">
        Créer
    </button>
  </form>

@endsection

resources/views/back/offre/edit.blade.php
@extends('layouts.templateBack')
@section('titre')
   Modifier l'offre '{{$offre->titre}}'
@stop

@section('contenu')

<text style='margin-left:10px;color:red;'>* Champs obligatoires</text>
<br> </br>

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

<form style='margin-left:10px;' method="POST" action="{{route('offre.update', $offre->id)}}" enctype="multipart/form-data">
@csrf
@method('PUT')
  <div class="form-group">
    <label for="Titre">Titre *</label>
    <input type="text" class="form-control" id="titre" name="titre" value="{{$offre->titre}}">
  </div>

  <div class="form-group">
    <label for="Intitule_poste">Intitulé du poste *</label>
    <input type="text" class="form-control" id="intitule" name="intitule"  value="{{$offre->intitule_poste}}"></textarea>
  </div>

  <div class="form-group">
    <label for="Secteur">Secteur *</label>
    <input type="text" class="form-control" id="secteur" name="secteur" value="{{$offre->secteur}}"></textarea>
  </div>

  <div class="form-group">
    <label for="Description">Description *</label>
    <input type="text" class="form-control" id="description" name="description" value="{{$offre->description}}">
  </div>

  <div class="form-group">
     <label for="Niveau">Niveau *</label>
     <select class="form-control" id="niveau" name="niveau">
       <option>BAC</option>
       <option>BTS</option>
       <option>Licence</option>
       <option>Autre</option>
       <option selected hidden>{{$offre->niveau}}</option>
     </select>
   </div>

   <div class="form-group">
    <label for="Upload">Ajouter un PDF</label>
     <div>
       <div>
         <label style="font-weight: 400;" for="inputGroupFile02">Remplacer :</label>
         <label style="font-weight: 700;" for="inputGroupFile02">
           <?php
           $value = $offre->pdf;
           $rest = substr($value, 34);
           echo $rest;

           if($rest == NULL){echo 'No file selected';};
          ?>
        </label>
          <label style="font-weight: 400;" for="inputGroupFile02"> par </label>
         <input type="file" id="file" name="file" onchange="handleFiles(this.files)">

       </div>
     </div>
  </div>

  <div class="form-group">
    <label for="Contrat">Contrat *</label>
    <select class="form-control" id="contrat" name="contrat">
       <option>CDD</option>
       <option>CDI</option>
       <option>Contrat de professionnalisation</option>
       <option>Contrat d apprentissage</option>
       <option selected hidden>{{$offre->type_contrat}}</option>
     </select>
  </div>

  <div class="form-group">
    <label for="Salaire">Salaire</label>
    <input type="text" class="form-control" id="salaire" name="salaire"  value="{{$offre->salaire}}"></textarea>
  </div>

  <div class="form-group">
     <label for="ENTREPRISE">Entreprise *</label>
     <select class="form-control" id="entreprise" name="entreprise">
       @foreach ($lesentreprises as $entreprise)
       <option value="{{ $entreprise->id }}">{{ $entreprise->nom }}</option>
       @endforeach
       <option value="{{$offre->entreprise->id}}" selected>{{ $offre->entreprise->nom }}</option>
     </select>
   </div>

    <button style='margin-bottom:10px;' type="submit" class="btn btn-primary">
        Modifier
    </button>
  </form>

@endsection

resources/views/back/offre/index.blade.php
@extends('layouts.templateBack')
@section('titre')
   Liste des Offres
@stop

@section('contenu')
<table class="table table-sm" id="table_id">

      <a href="{{route('offre.create')}}">
          <button style='margin-left:10px;' type="submit" class="btn btn-primary">
          Ajouter une offre
          </button>
      </a>
      <br> </br>

    @include('back.alert-message')

    <thead>
      <tr>
          <th scope="col">ID</th>
          <th scope="col">Titre</th>
          <th scope="col">Intitulé du poste</th>
          <th scope="col">Secteur</th>
          <th scope="col">Description</th>
          <th scope="col">Niveau</th>
          <th scope="col">Contrat</th>
          <th scope="col">PDF</th>
          <th scope="col">Salaire</th>
          <th scope="col" class="text-right">Action</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($lesOffres as $offre)
        <tr>

            <td> {{$offre->id}}</td>
            <td> {{$offre->titre}}</td>
            <td> {{$offre->intitule_poste}}</td>
            <td> {{$offre->secteur}}</td>
            <td> {{$offre->description}}</td>
            <td> {{$offre->niveau}}</td>
            <td> {{$offre->type_contrat}}</td>
            <?php
              $value = $offre->pdf;
              $rest = substr($value, 34);
              echo "<td>";
              echo $rest;
              if($rest == NULL){echo 'No file selected';};
              echo "</td>";
            ?>
            <td> {{$offre->salaire}}</td>

            <td class="td-actions text-right">
                <div style="display: inline-flex;">
            <form action="{{route('offre.edit', $offre->id)}}" method="POST">
              @csrf
              @method('GET')
              <button type="submit" rel="tooltip" class="btn btn-success btn-round">
                  <i class="material-icons">Modifier</i>
              </button>
            </form>
            </form>
            <form action="{{route('offre.destroy', $offre->id)}}" method="POST">
                @csrf
                @method('DELETE')
              <button type="submit" rel="tooltip" class="btn btn-danger btn-round" onclick="return confirm('Est tu sur de vouloir supprimer cette offre ?')">
                  <i class="material-icons">Supprimer</i>
              </button>
            </form>


              </div>
            </td>
          </tr>
        @endforeach
    </tbody>
  </table>
@stop

@section('script')
<script>
$(document).ready(function() {
        $('#table_id').DataTable({

            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
            },
            "order": [[ 0, "desc" ]],
        });
    });
</script>
@stop